version: '3'

services:
  intro_db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

