version: '3'

services:
  # intro_db:
  #   image: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: example_database
  #     MYSQL_USER: example_user
  #     MYSQL_PASSWORD: example_password
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3308:3306
  intro_db_index:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./sql-withindex:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306
  adminer:
    image: adminer
    ports:
      - "9091:8080"
