version: '3'

services:
  intro_db_master:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/master.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
  intro_db_slave:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./sql/slave.cnf:/etc/mysql/my.cnf
    depends_on:
      - intro_db_master
    ports:
      - 3307:3306
  adminer:
    image: adminer
    ports:
      - "9091:8080"
